# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_title', models.CharField(max_length=45, verbose_name='회의 제목')),
                ('conference_description', models.TextField(blank=True, verbose_name='회의 내용')),
                ('start_date', models.DateTimeField(verbose_name='회의 시작일시')),
                ('end_date', models.DateTimeField(verbose_name='회의 종료일시')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
            ],
            options={
                'db_table': 'res_conference_info',
            },
        ),
        migrations.CreateModel(
            name='ConferenceMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etc_member', models.CharField(max_length=45, verbose_name='그외 참석자')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.ConferenceInfo')),
            ],
            options={
                'db_table': 'res_conference_member',
            },
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=45, unique=True, verbose_name='회의실 이름')),
                ('room_desc', models.CharField(blank=True, max_length=200, verbose_name='회의실 설명')),
                ('room_capacity', models.IntegerField(default=0, verbose_name='수용 인원')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
            ],
            options={
                'db_table': 'res_room_info',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='사용자 이름')),
                ('email', models.EmailField(max_length=45, unique=True, verbose_name='사용자 이메일')),
                ('password', models.CharField(max_length=45, verbose_name='사용자 패스워드')),
                ('part_name', models.CharField(blank=True, max_length=45, verbose_name='사용자 소속부서')),
                ('valid_yn', models.CharField(default='Y', max_length=1, verbose_name='활성화 여부')),
                ('mobile_num', models.CharField(blank=True, max_length=11, verbose_name='핸드폰 번호')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
            ],
            options={
                'db_table': 'res_user',
            },
        ),
        migrations.AddField(
            model_name='conferencemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.UserInfo'),
        ),
        migrations.AddField(
            model_name='conferenceinfo',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.RoomInfo'),
        ),
        migrations.AddField(
            model_name='conferenceinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.UserInfo'),
        ),
    ]
