# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferenceinfo',
            options={'verbose_name': '회의 설정 정보', 'verbose_name_plural': '회의 설정 정보'},
        ),
        migrations.AlterModelOptions(
            name='conferencemember',
            options={'verbose_name': '참석자 정보', 'verbose_name_plural': '참석자 정보'},
        ),
        migrations.AlterModelOptions(
            name='roominfo',
            options={'verbose_name': '회의실 정보', 'verbose_name_plural': '회의실 정보'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '사용자 정보', 'verbose_name_plural': '사용자 정보'},
        ),
        migrations.AlterField(
            model_name='conferencemember',
            name='etc_member',
            field=models.CharField(blank=True, max_length=45, verbose_name='그외 참석자'),
        ),
    ]
