# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20180130_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceinfo',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference', to='reservation.RoomInfo'),
        ),
        migrations.AlterField(
            model_name='conferenceinfo',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='수정일시'),
        ),
        migrations.RemoveField(
            model_name='conferencemember',
            name='conference',
        ),
        migrations.AddField(
            model_name='conferencemember',
            name='conference',
            field=models.ManyToManyField(related_name='members', to='reservation.ConferenceInfo'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='수정일시'),
        ),
    ]
