# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20180131_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencemember',
            name='conference',
        ),
        migrations.AddField(
            model_name='conferencemember',
            name='conference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='reservation.ConferenceInfo'),
        ),
    ]
