# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('contents', models.CharField(max_length=500, verbose_name='본문내용')),
                ('cre_user', models.CharField(max_length=50, verbose_name='작성자')),
                ('cre_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일자')),
                ('upd_date', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일자')),
            ],
            options={
                'db_table': 'board',
                'ordering': ('-cre_date',),
            },
        ),
    ]
